test upload artifacts

diff --git a/.github/actions/upload-artifacts-to-s3-without-make/action.yml b/.github/actions/upload-artifacts-to-s3-without-make/action.yml
--- a/.github/actions/upload-artifacts-to-s3-without-make/action.yml
+++ b/.github/actions/upload-artifacts-to-s3-without-make/action.yml
@@ -24,6 +24,13 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: configure aws credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: arn:aws:iam::022044324644:role/GitHubRlecCi  
+        role-session-name: release_artifact_to_s3
+        aws-region: us-east-1
+
     - name: Configure AWS credentials and upload artifcats # todo - use aws role instead
       shell: bash
       run: |
@@ -32,20 +39,20 @@ runs:
           pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
           echo ::endgroup::
 
-          # Variables from the workflow
-          export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
-          export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
-          export AWS_REGION="us-east-1"
-          # Check if the required environment variables are set
-          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
-            echo "Missing AWS credentials or region configuration."
-            exit 1
-          fi
-          # Configure AWS CLI with provided credentials and region
-          echo "Configuring AWS CLI with access keys..."
-          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
-          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
-          aws configure set region "$AWS_REGION"
+          # # Variables from the workflow
+          # export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
+          # export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
+          # export AWS_REGION="us-east-1"
+          # # Check if the required environment variables are set
+          # if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
+          #   echo "Missing AWS credentials or region configuration."
+          #   exit 1
+          # fi
+          # # Configure AWS CLI with provided credentials and region
+          # echo "Configuring AWS CLI with access keys..."
+          # aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
+          # aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
+          # aws configure set region "$AWS_REGION"
 
           echo ::group::upload artifacts
             SNAPSHOT=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
