fixes 4

diff --git a/sbin/getgears b/sbin/getgears
--- a/sbin/getgears
+++ b/sbin/getgears
@@ -16,6 +16,7 @@ if [[ "$1" == "--help" || "$1" == "help" || "$HELP" == "1" ]]; then
 		Argument variables:
 		GEARS_OSNICK=nick   Get binaries for give osnick
 		GEARS_PATH=dir      Get binaries from given Gears repo
+		GEARS_BUILD=0|1     Build RedisGears
 		NOP=1               No operation
 		HELP=1              Show help
 
@@ -23,70 +24,7 @@ if [[ "$1" == "--help" || "$1" == "help" || "$HELP" == "1" ]]; then
 	exit 0
 fi
 
-OP=""
-[[ "$NOP" == "1" ]] && OP=echo
-
-os="$($READIES/bin/platform --os)"
-arch="$($READIES/bin/platform --arch)"
-GEARS_BASE_DIR="$ROOT/bin/$($READIES/bin/platform -t)"
-
-if [[ ! -z "$GEARS_PATH" ]]; then
-	platform="$($READIES/bin/platform -t)"
-else
-	dist="$($READIES/bin/platform --dist)"
-	nick="$($READIES/bin/platform --osnick)"
-
-	BUILD_GEARS=""
-	if [[ "$os" != "linux" || "$arch" != "x64" ]]; then
-		BUILD_GEARS=1
-	else
-		if [[ $dist == "ubuntu" ]]; then
-			if [[ $nick != "bionic" && $nick != "xenial" && $nick != "trusty" ]]; then
-				nick="bionic"
-			fi
-		elif [[ $dist == debian ]]; then
-			nick=bionic
-		elif [[ $dist == centos || $dist == redhat || $dist == fedora ]]; then
-			nick=centos7
-		elif [[ ! -z "$GEARS_OSNICK" ]]; then
-			nick=$GEARS_OSNICK
-		else
-			BUILD_GEARS=1
-		fi
-	fi
-	if [[ $BUILD_GEARS == 1 ]]; then
-		echo "Cannot match binary artifacts; build RedisGears"
-		mkdir -p $GEARS_BASE_DIR
-		git clone --recursive https://github.com/RedisGears/RedisGears.git
-		cd RedisGears
-		if ! make setup get_deps build; then
-			eprint "Build failed; build RedisGears and set GEARS_PATH"
-			exit 1
-		else
-			exit 0
-		fi
-	fi
-
-	platform="${os}-${nick}-${arch}"
-fi
-
-GEARS_S3_URL="http://redismodules.s3.amazonaws.com/redisgears/snapshots"
-GEARS_MOD="redisgears.${platform}.master.zip"
-GEARS_DEPS="redisgears-python.${platform}.master.tgz"
-
-FINAL_WORK_DIR="$GEARS_BASE_DIR/RedisGears"
-
-if [[ -d $FINAL_WORK_DIR && -f $FINAL_WORK_DIR/redisgears.so ]]; then
-	echo "RedisGears is in ${FINAL_WORK_DIR}"
-	exit 0
-fi
-
-$OP mkdir -p $(dirname $FINAL_WORK_DIR)
-$OP rm -rf ${FINAL_WORK_DIR}.*
-WORK_DIR=$(mktemp -d ${FINAL_WORK_DIR}.XXXXXX)
-$OP mkdir -p $WORK_DIR
-
-if [[ -z $GEARS_PATH ]]; then
+download_gears() {
 	F_GEARS_MOD="$WORK_DIR/$GEARS_MOD"
 	if [[ ! -f $F_GEARS_MOD ]]; then
 		echo "Downloading RedisGears ..."
@@ -104,6 +42,90 @@ if [[ -z $GEARS_PATH ]]; then
 	else
 		echo "Found RedisGears dependencies at $F_GEARS_DEPS"
 	fi
+}
+
+build_gears() {
+	$OP cd $ROOT/deps
+	if [[ ! -d RedisGears ]]; then
+		runn git clone --recursive https://github.com/RedisGears/RedisGears.git
+	fi
+	$OP cd RedisGears
+	if [[ ! -f artifacts/snapshot/redisgears.${platform}.master.zip ]]; then
+		runn make setup get_deps all
+	fi
+	export GEARS_PATH=$ROOT/deps/RedisGears
+		
+}
+
+install_gears() {
+	$OP unzip -q $F_GEARS_MOD -d $WORK_DIR
+	$OP tar --no-same-owner -C $WORK_DIR -xzf $F_GEARS_DEPS
+	$OP mv $WORK_DIR $FINAL_WORK_DIR
+}
+
+OP=""
+[[ "$NOP" == "1" ]] && OP=echo
+
+os="$($READIES/bin/platform --os)"
+arch="$($READIES/bin/platform --arch)"
+
+if [[ ! -z "$GEARS_PATH" ]]; then
+	platform="$($READIES/bin/platform -t)"
+else
+	dist="$($READIES/bin/platform --dist)"
+	nick="$($READIES/bin/platform --osnick)"
+
+	GEARS_BUILD=${GEARS_BUILD:-0}
+	if [[ $GEARS_BUILD != 1 ]]; then
+		if [[ "$os" != "linux" || "$arch" != "x64" ]]; then
+			echo "Cannot match binary artifacts; build RedisGears"
+			GEARS_BUILD=1
+		else
+			if [[ $dist == "ubuntu" ]]; then
+				if [[ $nick != "bionic" && $nick != "xenial" && $nick != "trusty" ]]; then
+					nick="bionic"
+				fi
+			elif [[ $dist == debian ]]; then
+				nick=bionic
+			elif [[ $dist == centos || $dist == redhat || $dist == fedora ]]; then
+				nick=centos7
+			elif [[ ! -z "$GEARS_OSNICK" ]]; then
+				nick=$GEARS_OSNICK
+			else
+				echo "Cannot match binary artifacts; build RedisGears"
+				GEARS_BUILD=1
+			fi
+		fi
+	fi
+
+	platform="${os}-${nick}-${arch}"
+
+	if [[ $GEARS_BUILD == 1 ]]; then
+		if ! build_gears; then
+			eprint "Build failed; build RedisGears and set GEARS_PATH"
+			exit 1
+		fi
+	fi
+fi
+
+GEARS_S3_URL="http://redismodules.s3.amazonaws.com/redisgears/snapshots"
+GEARS_MOD="redisgears.${platform}.master.zip"
+GEARS_DEPS="redisgears-python.${platform}.master.tgz"
+
+FINAL_WORK_DIR="$ROOT/bin/$($READIES/bin/platform -t)/RedisGears"
+
+if [[ -d $FINAL_WORK_DIR && -f $FINAL_WORK_DIR/redisgears.so ]]; then
+	echo "RedisGears is in ${FINAL_WORK_DIR}"
+	exit 0
+fi
+
+$OP mkdir -p $(dirname $FINAL_WORK_DIR)
+$OP rm -rf ${FINAL_WORK_DIR}.*
+WORK_DIR=$(mktemp -d ${FINAL_WORK_DIR}.XXXXXX)
+$OP mkdir -p $WORK_DIR
+
+if [[ -z $GEARS_PATH ]]; then
+	download_gears
 else
 	F_GEARS_MOD="${GEARS_PATH}/artifacts/snapshot/${GEARS_MOD}"
 	F_GEARS_DEPS="${GEARS_PATH}/artifacts/snapshot/${GEARS_DEPS}"
@@ -111,6 +133,4 @@ else
 	[[ ! -f $F_GEARS_DEPS ]] && { eprint "$F_GEARS_DEPS is missing"; exit 1; }
 fi
 
-$OP unzip -q $F_GEARS_MOD -d $WORK_DIR
-$OP tar --no-same-owner -C $WORK_DIR -xzf $F_GEARS_DEPS
-$OP mv $WORK_DIR $FINAL_WORK_DIR
+install_gears
